;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        goto-last-change
        paredit-close-square
        paredit-open-square
        paredit-semicolon
        paredit-wrap-round
        smex
        swiper
        ))

(setq mc/cmds-to-run-once
      '(
        swiper-mc
        ))
